using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Shipper2.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<ShipperContext>
    {
        protected override void Seed(ShipperContext context)
        {
            var productCategories = new List<ProductCategory>
            {
                new ProductCategory { Name = "Rock" },
                new ProductCategory { Name = "Jazz" },
                new ProductCategory { Name = "Metal" },
                new ProductCategory { Name = "Alternative" },
                new ProductCategory { Name = "Disco" },
                new ProductCategory { Name = "Blues" },
                new ProductCategory { Name = "Latin" },
                new ProductCategory { Name = "Reggae" },
                new ProductCategory { Name = "Pop" },
                new ProductCategory { Name = "Classical" }
            };

            var retailers = new List<Retailer>
            {
                new Retailer { Name = "Aaron Copland & London Symphony Orchestra" },
                new Retailer { Name = "Aaron Goldberg" },
                new Retailer { Name = "AC/DC" },
                new Retailer { Name = "Accept" },
                new Retailer { Name = "Adrian Leaper & Doreen de Feis" },
                new Retailer { Name = "Aerosmith" },
                new Retailer { Name = "Aisha Duo" },
                new Retailer { Name = "Alanis Morissette" },
                new Retailer { Name = "Alberto Turco & Nova Schola Gregoriana" },
                new Retailer { Name = "Alice In Chains" },
                new Retailer { Name = "Amy Winehouse" },
                new Retailer { Name = "Anita Ward" },
                new Retailer { Name = "Antônio Carlos Jobim" },
                new Retailer { Name = "Apocalyptica" },
                new Retailer { Name = "Audioslave" },
                new Retailer { Name = "Barry Wordsworth & BBC Concert Orchestra" },
                new Retailer { Name = "Berliner Philharmoniker & Hans Rosbaud" },
                new Retailer { Name = "Berliner Philharmoniker & Herbert Von Karajan" },
                new Retailer { Name = "Billy Cobham" },
                new Retailer { Name = "Black Label Society" },
                new Retailer { Name = "Black Sabbath" },
                new Retailer { Name = "Boston Symphony Orchestra & Seiji Ozawa" },
                new Retailer { Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Retailer { Name = "Bruce Dickinson" },
                new Retailer { Name = "Buddy Guy" },
                new Retailer { Name = "Caetano Veloso" },
                new Retailer { Name = "Cake" },
                new Retailer { Name = "Calexico" },
                new Retailer { Name = "Cássia Eller" },
                new Retailer { Name = "Chic" },
                new Retailer { Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Retailer { Name = "Chico Buarque" },
                new Retailer { Name = "Chico Science & Nação Zumbi" },
                new Retailer { Name = "Choir Of Westminster Abbey & Simon Preston" },
                new Retailer { Name = "Chris Cornell" },
                new Retailer { Name = "Christopher O'Riley" },
                new Retailer { Name = "Cidade Negra" },
                new Retailer { Name = "Cláudio Zoli" },
                new Retailer { Name = "Creedence Clearwater Revival" },
                new Retailer { Name = "David Coverdale" },
                new Retailer { Name = "Deep Purple" },
                new Retailer { Name = "Dennis Chambers" },
                new Retailer { Name = "Djavan" },
                new Retailer { Name = "Donna Summer" },
                new Retailer { Name = "Dread Zeppelin" },
                new Retailer { Name = "Ed Motta" },
                new Retailer { Name = "Edo de Waart & San Francisco Symphony" },
                new Retailer { Name = "Elis Regina" },
                new Retailer { Name = "English Concert & Trevor Pinnock" },
                new Retailer { Name = "Eric Clapton" },
                new Retailer { Name = "Eugene Ormandy" },
                new Retailer { Name = "Faith No More" },
                new Retailer { Name = "Falamansa" },
                new Retailer { Name = "Foo Fighters" },
                new Retailer { Name = "Frank Zappa & Captain Beefheart" },
                new Retailer { Name = "Fretwork" },
                new Retailer { Name = "Funk Como Le Gusta" },
                new Retailer { Name = "Gerald Moore" },
                new Retailer { Name = "Gilberto Gil" },
                new Retailer { Name = "Godsmack" },
                new Retailer { Name = "Gonzaguinha" },
                new Retailer { Name = "Göteborgs Symfoniker & Neeme Järvi" },
                new Retailer { Name = "Guns N' Roses" },
                new Retailer { Name = "Gustav Mahler" },
                new Retailer { Name = "Incognito" },
                new Retailer { Name = "Iron Maiden" },
                new Retailer { Name = "James Levine" },
                new Retailer { Name = "Jamiroquai" },
                new Retailer { Name = "Jimi Hendrix" },
                new Retailer { Name = "Joe Satriani" },
                new Retailer { Name = "Jorge Ben" },
                new Retailer { Name = "Jota Quest" },
                new Retailer { Name = "Judas Priest" },
                new Retailer { Name = "Julian Bream" },
                new Retailer { Name = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                new Retailer { Name = "Kiss" },
                new Retailer { Name = "Led Zeppelin" },
                new Retailer { Name = "Legião Urbana" },
                new Retailer { Name = "Lenny Kravitz" },
                new Retailer { Name = "Les Arts Florissants & William Christie" },
                new Retailer { Name = "London Symphony Orchestra & Sir Charles Mackerras" },
                new Retailer { Name = "Luciana Souza/Romero Lubambo" },
                new Retailer { Name = "Lulu Santos" },
                new Retailer { Name = "Marcos Valle" },
                new Retailer { Name = "Marillion" },
                new Retailer { Name = "Marisa Monte" },
                new Retailer { Name = "Martin Roscoe" },
                new Retailer { Name = "Maurizio Pollini" },
                new Retailer { Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                new Retailer { Name = "Men At Work" },
                new Retailer { Name = "Metallica" },
                new Retailer { Name = "Michael Tilson Thomas & San Francisco Symphony" },
                new Retailer { Name = "Miles Davis" },
                new Retailer { Name = "Milton Nascimento" },
                new Retailer { Name = "Mötley Crüe" },
                new Retailer { Name = "Motörhead" },
                new Retailer { Name = "Nash Ensemble" },
                new Retailer { Name = "Nicolaus Esterhazy Sinfonia" },
                new Retailer { Name = "Nirvana" },
                new Retailer { Name = "O Terço" },
                new Retailer { Name = "Olodum" },
                new Retailer { Name = "Orchestra of The Age of Enlightenment" },
                new Retailer { Name = "Os Paralamas Do Sucesso" },
                new Retailer { Name = "Ozzy Osbourne" },
                new Retailer { Name = "Page & Plant" },
                new Retailer { Name = "Paul D'Ianno" },
                new Retailer { Name = "Pearl Jam" },
                new Retailer { Name = "Pink Floyd" },
                new Retailer { Name = "Queen" },
                new Retailer { Name = "R.E.M." },
                new Retailer { Name = "Raul Seixas" },
                new Retailer { Name = "Red Hot Chili Peppers" },
                new Retailer { Name = "Roger Norrington, London Classical Players" },
                new Retailer { Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                new Retailer { Name = "Rush" },
                new Retailer { Name = "Santana" },
                new Retailer { Name = "Scholars Baroque Ensemble" },
                new Retailer { Name = "Scorpions" },
                new Retailer { Name = "Sergei Prokofiev & Yuri Temirkanov" },
                new Retailer { Name = "Sir Georg Solti & Wiener Philharmoniker" },
                new Retailer { Name = "Skank" },
                new Retailer { Name = "Soundgarden" },
                new Retailer { Name = "Spyro Gyra" },
                new Retailer { Name = "Stevie Ray Vaughan & Double Trouble" },
                new Retailer { Name = "Stone Temple Pilots" },
                new Retailer { Name = "System Of A Down" },
                new Retailer { Name = "Temple of the Dog" },
                new Retailer { Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
                new Retailer { Name = "The 12 Cellists of The Berlin Philharmonic" },
                new Retailer { Name = "The Black Crowes" },
                new Retailer { Name = "The Cult" },
                new Retailer { Name = "The Doors" },
                new Retailer { Name = "The King's Singers" },
                new Retailer { Name = "The Police" },
                new Retailer { Name = "The Posies" },
                new Retailer { Name = "The Rolling Stones" },
                new Retailer { Name = "The Who" },
                new Retailer { Name = "Tim Maia" },
                new Retailer { Name = "Ton Koopman" },
                new Retailer { Name = "U2" },
                new Retailer { Name = "UB40" },
                new Retailer { Name = "Van Halen" },
                new Retailer { Name = "Various Retailers" },
                new Retailer { Name = "Velvet Revolver" },
                new Retailer { Name = "Vinícius De Moraes" },
                new Retailer { Name = "Wilhelm Kempff" },
                new Retailer { Name = "Yehudi Menuhin" },
                new Retailer { Name = "Yo-Yo Ma" },
                new Retailer { Name = "Zeca Pagodinho" }
            };

            new List<Product>
            {
                new Product { Name = "A Copland Celebration, Vol. I", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Aaron Copland & London Symphony Orchestra"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Worlds", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Aaron Goldberg"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "For Those About To Rock We Salute You", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "AC/DC"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Let There Be Rock", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "AC/DC"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Balls to the Wall", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Accept"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Restless and Wild", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Accept"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Górecki: Symphony No. 3", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Adrian Leaper & Doreen de Feis"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Big Ones", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Aerosmith"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Quiet Songs", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Aisha Duo"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Jagged Little Pill", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Alanis Morissette"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Facelift", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Alice In Chains"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Frank", ProductCategory = productCategories.Single(g => g.Name == "Pop"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Amy Winehouse"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ring My Bell", ProductCategory = productCategories.Single(g => g.Name == "Disco"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Anita Ward"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chill: Brazil (Disc 2)", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Antônio Carlos Jobim"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Warner 25 Anos", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Antônio Carlos Jobim"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Plays Metallica By Four Cellos", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Apocalyptica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Revelations", ProductCategory = productCategories.Single(g => g.Name == "Alternative"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Audioslave"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Audioslave", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Audioslave"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Last Night of the Proms", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Barry Wordsworth & BBC Concert Orchestra"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Sibelius: Finlandia", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Berliner Philharmoniker & Hans Rosbaud"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mozart: Symphonies Nos. 40 & 41", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Berliner Philharmoniker & Herbert Von Karajan"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of Billy Cobham", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Billy Cobham"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Alcohol Fueled Brewtality Live! [Disc 1]", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Black Label Society"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Alcohol Fueled Brewtality Live! [Disc 2]", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Black Label Society"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Black Sabbath Vol. 4 (Remaster)", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Black Sabbath"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Black Sabbath", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Black Sabbath"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Carmina Burana", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Boston Symphony Orchestra & Seiji Ozawa"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Soprano Inspired", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chemical Wedding", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Bruce Dickinson"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Prenda Minha", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Caetano Veloso"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Sozinho Remix Ao Vivo", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Caetano Veloso"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Cake: B-Sides and Rarities", ProductCategory = productCategories.Single(g => g.Name == "Alternative"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Cake"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Carried to Dust (Bonus Track Version)", ProductCategory = productCategories.Single(g => g.Name == "Alternative"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Calexico"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Cássia Eller - Sem Limite [Disc 1]", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Cássia Eller"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Le Freak", ProductCategory = productCategories.Single(g => g.Name == "Disco"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Chic"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Scheherazade", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Minha Historia", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Chico Buarque"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Afrociberdelia", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Chico Science & Nação Zumbi"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Da Lama Ao Caos", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Chico Science & Nação Zumbi"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Carry On", ProductCategory = productCategories.Single(g => g.Name == "Alternative"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Chris Cornell"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "SCRIABIN: Vers la flamme", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Christopher O'Riley"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Acústico MTV [Live]", ProductCategory = productCategories.Single(g => g.Name == "Reggae"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Cidade Negra"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Cidade Negra - Hits", ProductCategory = productCategories.Single(g => g.Name == "Reggae"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Cidade Negra"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Na Pista", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Cláudio Zoli"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chronicle, Vol. 1", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Creedence Clearwater Revival"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chronicle, Vol. 2", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Creedence Clearwater Revival"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Into The Light", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "David Coverdale"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Come Taste The Band", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Deep Purple In Rock", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Fireball", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Machine Head", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "MK III The Final Concerts [Disc 1]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Purpendicular", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Slaves And Masters", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Stormbringer", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Battle Rages On", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Final Concerts (Disc 2)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Deep Purple"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Outbreak", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Dennis Chambers"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Djavan Ao Vivo - Vol. 02", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Djavan"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Djavan Ao Vivo - Vol. 1", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Djavan"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "MacArthur Park Suite", ProductCategory = productCategories.Single(g => g.Name == "Disco"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Donna Summer"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Un-Led-Ed", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Dread Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best of Ed Motta", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ed Motta"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Adams, John: The Chairman Dances", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Edo de Waart & San Francisco Symphony"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Elis Regina-Minha História", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Elis Regina"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Pachelbel: Canon & Gigue", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "English Concert & Trevor Pinnock"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Unplugged", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Eric Clapton"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Cream Of Clapton", ProductCategory = productCategories.Single(g => g.Name == "Blues"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Eric Clapton"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Unplugged", ProductCategory = productCategories.Single(g => g.Name == "Blues"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Eric Clapton"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Respighi:Pines of Rome", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Eugene Ormandy"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Strauss: Waltzes", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Eugene Ormandy"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "King For A Day Fool For A Lifetime", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Faith No More"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Deixa Entrar", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Falamansa"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Your Honor [Disc 1]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Foo Fighters"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Your Honor [Disc 2]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Foo Fighters"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Colour And The Shape", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Foo Fighters"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bongo Fury", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Frank Zappa & Captain Beefheart"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Roda De Funk", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Funk Como Le Gusta"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Quanta Gente Veio Ver (Live)", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Gilberto Gil"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Quanta Gente Veio ver--Bônus De Carnaval", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Gilberto Gil"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Faceless", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Godsmack"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Meus Momentos", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Gonzaguinha"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Nielsen: The Six Symphonies", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Göteborgs Symfoniker & Neeme Järvi"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Appetite for Destruction", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Guns N' Roses"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Use Your Illusion I", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Guns N' Roses"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Use Your Illusion II", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Guns N' Roses"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Blue Moods", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Incognito"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Matter of Life and Death", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Brave New World", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Fear Of The Dark", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live At Donington 1992 (Disc 1)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live At Donington 1992 (Disc 2)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rock In Rio [CD2]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Number of The Beast", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The X Factor", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Virtual XI", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Real Dead One", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Real Live One", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live After Death", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "No Prayer For The Dying", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Piece Of Mind", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Powerslave", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rock In Rio [CD1]", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rock In Rio [CD2]", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Seventh Son of a Seventh Son", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Somewhere in Time", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Number of The Beast", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Iron Maiden", ProductCategory = productCategories.Single(g => g.Name == "Blues"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Iron Maiden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mascagni: Cavalleria Rusticana", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "James Levine"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Emergency On Planet Earth", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Jamiroquai"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Are You Experienced?", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Jimi Hendrix"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Surfing with the Alien (Remastered)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Joe Satriani"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Jorge Ben Jor 25 Anos", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Jorge Ben"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Jota Quest-1995", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Jota Quest"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Living After Midnight", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Judas Priest"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Weill: The Seven Deadly Sins", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Kent Nagano and Orchestre de l'Opéra de Lyon"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Kiss", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Kiss"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Unplugged [Live]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Kiss"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "BBC Sessions [Disc 1] [Live]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "BBC Sessions [Disc 2] [Live]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Coda", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Houses Of The Holy", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Through The Out Door", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "IV", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Led Zeppelin I", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Led Zeppelin II", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Led Zeppelin III", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Physical Graffiti [Disc 1]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Physical Graffiti [Disc 2]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Presence", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Song Remains The Same (Disc 1)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Song Remains The Same (Disc 2)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Led Zeppelin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mais Do Mesmo", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Legião Urbana"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits", ProductCategory = productCategories.Single(g => g.Name == "Reggae"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Lenny Kravitz"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Lenny Kravitz"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Lenny Kravitz"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Tchaikovsky: The Nutcracker", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "London Symphony Orchestra & Sir Charles Mackerras"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Duos II", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Luciana Souza/Romero Lubambo"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chill: Brazil (Disc 1)", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Marcos Valle"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Misplaced Childhood", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Marillion"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Barulhinho Bom", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Marisa Monte"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Szymanowski: Piano Works, Vol. 1", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Martin Roscoe"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of Men At Work", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Men At Work"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "...And Justice For All", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Black Product", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Garage Inc. (Disc 1)", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Garage Inc. (Disc 2)", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Load", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Master Of Puppets", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "ReLoad", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ride The Lightning", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "St. Anger", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Metallica"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Berlioz: Symphonie Fantastique", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Prokofiev: Romeo & Juliet", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Miles Ahead", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Miles Davis"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Essential Miles Davis [Disc 1]", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Miles Davis"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Essential Miles Davis [Disc 2]", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Miles Davis"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Milton Nascimento Ao Vivo", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Milton Nascimento"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Minas", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Milton Nascimento"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Motley Crue Greatest Hits", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Mötley Crüe"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ace Of Spades", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Motörhead"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mozart: Chamber Music", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Nash Ensemble"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best of Beethoven", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Nicolaus Esterhazy Sinfonia"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Nevermind", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Nirvana"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Compositores", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "O Terço"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Olodum", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Olodum"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: The Brandenburg Concertos", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Orchestra of The Age of Enlightenment"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Acústico MTV", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Os Paralamas Do Sucesso"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Arquivo II", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Os Paralamas Do Sucesso"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Arquivo Os Paralamas Do Sucesso", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Os Paralamas Do Sucesso"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Tribute", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ozzy Osbourne"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bark at the Moon (Remastered)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ozzy Osbourne"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Blizzard of Ozz", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ozzy Osbourne"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Diary of a Madman (Remastered)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ozzy Osbourne"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "No More Tears (Remastered)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ozzy Osbourne"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Speak of the Devil", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ozzy Osbourne"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Walking Into Clarksdale", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Page & Plant"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Beast Live", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Paul D'Ianno"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live On Two Legs [Live]", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Pearl Jam"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Riot Act", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Pearl Jam"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ten", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Pearl Jam"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Vs.", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Pearl Jam"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Dark Side Of The Moon", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Pink Floyd"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits I", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Queen"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits II", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Queen"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "News Of The World", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Queen"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "New Adventures In Hi-Fi", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "R.E.M."), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Raul Seixas", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Raul Seixas"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "By The Way", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Red Hot Chili Peppers"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Californication", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Red Hot Chili Peppers"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Purcell: The Fairy Queen", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Roger Norrington, London Classical Players"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Haydn: Symphonies 99 - 104", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Royal Philharmonic Orchestra & Sir Thomas Beecham"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Retrospective I (1974-1980)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Rush"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Santana - As Years Go By", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Santana"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Santana Live", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Santana"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Supernatural", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Santana"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Handel: The Messiah (Highlights)", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Scholars Baroque Ensemble"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Prokofiev: Symphony No.1", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Wagner: Favourite Overtures", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Sir Georg Solti & Wiener Philharmoniker"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Maquinarama", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Skank"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "O Samba Poconé", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Skank"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "A-Sides", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Soundgarden"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Heart of the Night", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Spyro Gyra"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Morning Dance", ProductCategory = productCategories.Single(g => g.Name == "Jazz"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Spyro Gyra"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Step", ProductCategory = productCategories.Single(g => g.Name == "Blues"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Stevie Ray Vaughan & Double Trouble"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Core", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Stone Temple Pilots"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mezmerize", ProductCategory = productCategories.Single(g => g.Name == "Metal"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "System Of A Down"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Temple of the Dog", ProductCategory = productCategories.Single(g => g.Name == "Alternative"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Temple of the Dog"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "[1997] Black Light Syndrome", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Terry Bozzio, Tony Levin & Steve Stevens"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "South American Getaway", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The 12 Cellists of The Berlin Philharmonic"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live [Disc 1]", ProductCategory = productCategories.Single(g => g.Name == "Blues"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Black Crowes"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live [Disc 2]", ProductCategory = productCategories.Single(g => g.Name == "Blues"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Black Crowes"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Beyond Good And Evil", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Cult"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Doors", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Doors"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "English Renaissance", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The King's Singers"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Police Greatest Hits", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Police"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Every Kind of Light", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Posies"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Hot Rocks, 1964-1971 (Disc 1)", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Rolling Stones"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "No Security", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Rolling Stones"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Voodoo Lounge", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Rolling Stones"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "My Generation - The Very Best Of The Who", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "The Who"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Serie Sem Limite (Disc 1)", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Tim Maia"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Serie Sem Limite (Disc 2)", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Tim Maia"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: Toccata & Fugue in D Minor", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Ton Koopman"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Achtung Baby", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "B-Sides 1980-1990", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "How To Dismantle An Atomic Bomb", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Pop", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rattle And Hum", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of 1980-1990", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "War", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Zooropa", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "U2"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "UB40 The Best Of - Volume Two [UK]", ProductCategory = productCategories.Single(g => g.Name == "Reggae"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "UB40"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Diver Down", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Van Halen"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of Van Halen, Vol. I", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Van Halen"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Van Halen III", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Van Halen"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Van Halen", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Van Halen"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Axé Bahia 2001", ProductCategory = productCategories.Single(g => g.Name == "Pop"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Various Retailers"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Sambas De Enredo 2001", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Various Retailers"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Vozes do MPB", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Various Retailers"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Contraband", ProductCategory = productCategories.Single(g => g.Name == "Rock"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Velvet Revolver"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Vinicius De Moraes", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Vinícius De Moraes"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: Goldberg Variations", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Wilhelm Kempff"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bartok: Violin & Viola Concertos", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Yehudi Menuhin"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: The Cello Suites", ProductCategory = productCategories.Single(g => g.Name == "Classical"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Yo-Yo Ma"), ProductImage = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ao Vivo [IMPORT]", ProductCategory = productCategories.Single(g => g.Name == "Latin"), Price = 8.99M, Retailer = retailers.Single(a => a.Name == "Zeca Pagodinho"), ProductImage = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Products.Add(a));
        }
    }
}